#------------------------------------------------------------------------------
# General
#------------------------------------------------------------------------------
name: "Noorinbee Dispatch"
description: "Local, friendly, responsive."
language: "en"


#------------------------------------------------------------------------------
# Markdown processor and code highlighting
#------------------------------------------------------------------------------
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

#------------------------------------------------------------------------------
# Pagination and friendly URLs
#------------------------------------------------------------------------------
paginate: 48
paginate_path: /page-:num
permalink: /:title

#------------------------------------------------------------------------------
# Social sharing, comments and RSS.
#------------------------------------------------------------------------------
#disqus-id: yourusername

enable-share: true
#twitter: yourusername
github: yourusername
#google: +yourusername

rss-feed-limit: 10
rss-show-full: false

#------------------------------------------------------------------------------
# Configuration, plugins, gems, etc..
#------------------------------------------------------------------------------
baseurl: ''
url: "https://noorinbee-dispatcher.github.io/"
source: .
destination: ./_site
gems: ['jekyll-paginate']
collections_dir: realms
collections:
  - nature
collections:
  nature:
    output: true

sass:
    style: :compressed
    sass_dir: assets/css/